### ISSUE TITLE
Chart.js 3.0 support

### ISSUE THREAD

**Issue by benmccann** [samber/chartjs-plugin-datasource-prometheus#12]
Chart.js 3.0 is out now, so it might be nice for this plugin to upgrade to it

**Comment by alexbakker** [comment]
Is anyone currently working on this? If not, I might give it a shot.

**Comment by samber** [comment]
@alexbakker sure!

https://www.chartjs.org/docs/latest/getting-started/v3-migration.html

Looks like the support of momentjs has changed.

Data model of axes and scales are a bit different.

Metadata API has changed, but I'm pretty sure we are not concerned about that.

In case you have a better understanding of the work for the update. Feel free to share a simple todo-list. ;)

**Comment by samber** [comment]
Closing as we upgraded to chartjs 4
