### ISSUE TITLE
Exclude empty label set from caption

### ISSUE THREAD

**Issue by temppost2** [samber/chartjs-plugin-datasource-prometheus#18]
Sometimes for some reasons I exclude any labels from resulting time series data.
In this case we have captions of resulting charts in the form like: **node_load1{}**, **node_load5{}**, etc.
Is it possible to switch off drawing of empty label sets?

![image](https://user-images.githubusercontent.com/3591820/164718649-307de769-6121-42ed-8148-54af0c95d30a.png)

**Comment by samber** [comment]
I'm not sure to understand your need, but did you try the `dataSetHook` hook?

**Comment by temppost2** [comment]
I think **dataSetHook** is not an option, because there is no need to modify data set.
I just want to transform **node_load1{}** to **node_load** when it is rendered.

**Comment by samber** [comment]
Ok, you would like to rename the series name.

Feel free to open a PR to add a hook. The code is quite simple.

**Comment by temppost2** [comment]
Sorry, I was wrong. **dataSetHook** is quite a nice place where it could be performed.
