### ISSUE TITLE
baseURL as public parameter

### ISSUE THREAD

**Issue by matth-c3** [samber/chartjs-plugin-datasource-prometheus#2]
Hello @samber , 

Thanks for this grat plugin. 

Would it be possible to make the [internal parameter](https://github.com/samber/chartjs-plugin-datasource-prometheus/blob/d01d8a6961cac54059dcc06bfcea3dab57ba9efe/dist/chartjs-plugin-datasource-prometheus.umd.js#L1732) `baseURL` public ? 

```
...
baseURL: this.endpoint + "/api/v1/",
 ...
```

something like this could be done [here](https://github.com/samber/chartjs-plugin-datasource-prometheus/blob/d01d8a6961cac54059dcc06bfcea3dab57ba9efe/dist/chartjs-plugin-datasource-prometheus.umd.js#L1720-L1725): 

```
...
this.endpoint = options.endpoint.replace(/\/$/, "");
this.baseURL = options.baseURL || this.endpoint + "/api/v1/",
...
```

then [here](https://github.com/samber/chartjs-plugin-datasource-prometheus/blob/d01d8a6961cac54059dcc06bfcea3dab57ba9efe/dist/chartjs-plugin-datasource-prometheus.umd.js#L1732)

```
...
baseURL: this.baseURL,
...
```

instead of :

```
...
baseURL: this.endpoint + "/api/v1/",,
...
```

My use case is that I proxy the request via a custom application and the url in my case would need to look like this when reaching my app: 

- `https://my_super_app.com/prometheus?something=abc?somethingElse=efg`

Then I manage the construction of the URL in my backend to format the URL as necessary.

Thanks

**Comment by samber** [comment]
Hi @matth-c3 

Thanks for your suggestion.

I updated the `prometheus-query` package and upgraded dependencies of `chartjs-plugin-datasource-prometheus`.

Please install v0.2.0.

This lib is very young, feel free to open PRs to improve it. Contributions from the community are welcome! ;)

**Comment by matth-c3** [comment]
Hello @samber , 

Thanks, amazing work, I found out your plugin, it's awesome :D
