### ISSUE TITLE
[feature] Histogram chart

### ISSUE THREAD

**Issue by stokito** [samber/chartjs-plugin-datasource-prometheus#23]
Is it possible to draw a Histogram metric like request latency?

Thank you for the library, it's saved me.

**Comment by samber** [comment]
I never tested histograms.

As a good start, please replace `type: 'line'` by `type: 'bar'`. I'm pretty confident it should work as is.

**Comment by mnutt** [comment]
Bar (and stacked bar) now work in 2.0. I'm not sure if that alone is enough to get histograms working.

**Comment by samber** [comment]
ok, thanks @mnutt for the test

i will update the doc
