### ISSUE TITLE
Please use git tags for versions

### ISSUE THREAD

**Issue by stokito** [samber/chartjs-plugin-datasource-prometheus#32]
You can add a git tag v2.0.0 and then on the releases page create a release from the tag https://github.com/samber/chartjs-plugin-datasource-prometheus/releases

    git tag v2.0.0
    git push --tags

**Comment by samber** [comment]
I just created a tag and a release for both v2.0 and v2.1.

**Comment by stokito** [comment]
Thank you, now we can see list of changes https://github.com/samber/chartjs-plugin-datasource-prometheus/compare/v2.0.0...v2.1.0
