### ISSUE TITLE
Updating chart queries 

### ISSUE THREAD

**Issue by waleplanet** [samber/chartjs-plugin-datasource-prometheus#38]
Hi I am using this plugin to display a website via cdn.
Trying to update the chart query with this code does not update the chart or send a request to the backend

`chart.options.plugins['datasource-prometheus'].query = "new query";
chart.update({});`

**Comment by samber** [comment]
It works on demo: https://samber.github.io/chartjs-plugin-datasource-prometheus/example/

Can you tell me what version of datasource-prometheus and chartjs you are using ?

**Comment by waleplanet** [comment]
chart.js@4
chartjs-plugin-datasource-prometheus@2

it only updates when the timeRange field is updated
