### ISSUE TITLE
Why this code doesn't display graphic ?

### ISSUE THREAD

**Issue by elderwann** [samber/chartjs-plugin-datasource-prometheus#44]
Hello, thank you for nice tutorial, I try to apply it but the result in not perfect. 
The context :
- Flask server 1.0.2 
- Python 3.7.3
- Prometheus 2.26.0    ( difference with prometheus-query ? )

Flask server & Prometheus works perfectly.

I want to import data into chartjs html page from prometheus (using chartjs-plugin-datasource-prometheus). Here is the code :

`

<!DOCTYPE html> <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="fr" >

   <head>
	<meta name="description" content="Interface" />
	<meta name="Copyright" CONTENT="Alstom" />
	<meta name="expires" CONTENT="never" />
	<meta name="audience" CONTENT="all" />
	<meta name="Language" CONTENT="En" />
   
	<title>H M I</title>
	<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
	<link rel="shortcut icon" type="image/x-icon" href="/staticFiles/favicon.ico" />
	<link rel="stylesheet" media="screen" type="text/css" title="Design" href="/staticFiles/form.css"/>
	<link rel="SHORTCUT ICON" href="/staticFiles/favicon.ico">
	   
	<script src="/staticFiles/socket.io.js"></script> 
	<script src="/staticFiles/Chart.js"></script> 
	<script src="/staticFiles/jquery.min.js"></script> 
	<script src="/staticFiles/chartjs-adapter-date-fns.bundle.min.js"></script> 
	<script src="/staticFiles/chartjs-adapter-moment.js"></script> 
	<script	src="/staticFiles/chartjs-adapter-luxon.js"></script> 
	<script src="/staticFiles/moment.js"></script>
	<script src="/staticFiles/luxon.js"></script>	   
	<script src="/staticFiles/prometheus-query.umd.min.js"></script>
	<script src="/staticFiles/chartjs-plugin-datasource-prometheus.umd.js"></script>
   </head>
   <body>
   
	   	<div id="main_graph">
		
			<div id="mainleft">
				<a href="{{ url_for('index') }}">
					<img src="/staticFiles/image.png" class="favorite img1" alt="  " />
				</a>
			</div>
			
			
			<div id="mainright">
					<h1> Tool</h1>
			</div>	

			
			<div id="mastercenter_graph">

				<canvas id="myChart" style="width:100%;max-width:900px"></canvas>
				

				<script>

					Chart.registry.plugins.register(ChartDatasourcePrometheusPlugin);

					var myChart = new Chart(ctx, {
					  type: 'line',
					  plugins: [ChartDatasourcePrometheusPlugin],
					  options: {
					    plugins: {
					      'datasource-prometheus': {
					        prometheus: {
					          endpoint: "https://prometheus.demo.do.prometheus.io",
					          baseURL: "/api/v1",
					        },
					        query: 'sum by (job) (memory_usage_p)',
					        timeRange: {
					          type: 'relative',

					          // from 12 hours ago to now
					          start: -12 * 60 * 60 * 1000,
					          end: 0,
					        },
					      },
					    },
					  },
					});

				</script>
			
			</div>
			
		</div> 

    </body>
</html>

`

Thank for your help.

**Comment by elderwann** [comment]
Ok, I strongly suppose the .js file are the cause of my problem. So how can I change this : 

`

  <script src="https://cdn.jsdelivr.net/npm/chart.js@4/dist/chart.umd.min.js" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/chartjs-adapter-date-fns@3/dist/chartjs-adapter-date-fns.bundle.min.js" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-datasource-prometheus@2/dist/chartjs-plugin-datasource-prometheus.umd.min.js" crossorigin="anonymous"></script>
  <script>
`

To local access ? 
I use a raspberry, with Flask server.
Thank you so much.

**Comment by elderwann** [comment]
Hello, the mistake is when I try to pass a start value from a select form. But I finally succeed with  this code. Maybe this code is not very clean, but I works...

`


					<div class="container">
						<form id="refresh-form">
						
						
						
							
							<select id="startval" >
								<option value=-1000 >1s</option>
								<option value=-10000 >10s</option>
								<option value=-30000 >30s</option>
								<option value=-300000 >5min</option>
								<option value=-3600000 select="selected">1hr</option>
								<option value=-86400000 >1j</option>
							</select>			
						 
						</form>
					</div>

					<div id="myChart">
						<canvas></canvas>
					</div>				

					<br></br>

					<script>
					const form = document.querySelector('form#refresh-form');
					//const endpointInput = document.querySelector('form#refresh-form input#endpoint');
					//const queryInput = document.querySelector('form#refresh-form input#query');
					const startInput = Number(document.querySelector('form#refresh-form input#startval'));
					const test = document.querySelector('form#refresh-form select#startval');
					const ctx = document.querySelector('#myChart canvas').getContext('2d');
				
					//endpointInput.value = 'http://192.168.1.80:9090/';
					//queryInput.value = 'sum by (job) (memory_usage_p)';
					//startInput.value = '-10000';
					
					
					const start = -1 * 60 * 60 * 100; //
					const end = 0; // now
					const step = 3;
					
					
					const myChart = new Chart(ctx, {
						type: 'line',
						plugins: [ChartDatasourcePrometheusPlugin],
						options: {
											
							animation: {
								duration: 0,
							},
							scales: {
									y: {
									suggestedMin: 0,
									suggestedMax: 100
								}
							},
							legend: {
									display: true,
									labels: {
											color: 'rgb(255, 99, 132)',
									}
							},
							plugins: {
							
									subtitle: {
										display: false,
										text: 'Title of the Graph',
										color: 'rgb(255, 99, 132)',
									},
							

								'datasource-prometheus': {
									prometheus: {
										endpoint: 'http://192.168.1.80:9090/',
									},
									//query: ['node_load1', 'node_load5', 'node_load15'],
									query: 'sum by (job) (memory_usage_p)',

									timeRange: {
										type: 'relative',
										start: startInput,
										end: end,
										step: step,
										msUpdateInterval: 10000,
									},
									drawActiveElementsOnTop: false,
									tension: 0,  // Bezier curve tension of the line. Set to 0 to draw straightlines. This option is ignored if monotone cubic interpolation is used.
									fill: {
										target: 'origin',  // coloration under the line
										above: 'rgb(255, 182, 182)',   // Area will be red above the origin
										below: 'rgb(0, 0, 0)',    // And blue below the origin
									},
									

								},
							},
						},
					});
					
					
					var elt = document.querySelector('select');
					elt.addEventListener('change', function () {
						console.log('value => '+this.value);
						myChart.options.plugins['datasource-prometheus'].timeRange.start = + this.value;
						myChart.update();
					})


			//		form.addEventListener('submit', (event) => {
			//			event.preventDefault();
			//			myChart.options.plugins['datasource-prometheus'].prometheus.endpoint = endpointInput.value;
			//			myChart.options.plugins['datasource-prometheus'].query = queryInput.value;
						//myChart.options.plugins['datasource-prometheus'].timeRange.start = startInput;
			//			alert(startInput);
			//			myChart.update();
			//		});
									
					
					</script>

`

Thank you if you can check the code...
Regards.

**Comment by samber** [comment]
you told me it works, then ask me to check the code...

what is your issue ?

**Comment by samber** [comment]
ok, i'm closing then ;)
