### ISSUE TITLE
Multiple queries on a single chart

### ISSUE THREAD

**Issue by mcphlen** [samber/chartjs-plugin-datasource-prometheus#6]
Hello,
Thank you for this helpful plugin!

I understand this is not to replace Grafana, but is there a way to feed more than one query to the chart ? 

My use case is to draw two lines, one for a total sum of type1 entities over time, and one for a sum of type2 entities overtime.
These come from two different prometheus metrics. 

I can't find a way to do it on the same chart.

Any idea or workaround ?

Thanks again!

**Comment by samber** [comment]
Yep ...from now ;)

Documentation => https://github.com/samber/chartjs-plugin-datasource-prometheus#multiple-queries-in-one-chart

If needed, you can display a separated yAxis on the right.
