### ISSUE TITLE
Update Prometheus Query version.

### ISSUE THREAD

**Issue by luizfer** [samber/chartjs-plugin-datasource-prometheus#9]
Related to this PR: https://github.com/samber/prometheus-query-js/pull/7

Shouldn't there be an update to the prometheus query library?

**Comment by luizfer** [comment]
![image](https://user-images.githubusercontent.com/6831788/107442811-6d2c3b80-6b16-11eb-92db-a3affe4c9888.png)
Today I installed the library and code that is like PrometheusQuery is still without the auth correction.

**Comment by samber** [comment]
Hi @luizfer 

I suppose this lib is still using the old version of prometheus-query-js.

Anyway, I made a large update on `prometheus-query-js@beta` on Sunday. I planned to finish this work during the week.

As soon as `prometheus-query-js@3` is out, I gonna update `chartjs-plugin-datasource-prometheus`.

Feel free to shake me next Friday if it's not done ;)

**Comment by luizfer** [comment]
Thank you very much for the feedback, 
I have also observed the updates that you have made in the `prometheus-query`. I await your update here too.
I really liked the idea of ​​the project, count on my help.

I keep following the repository updates
